name: Pytest with python-3.11

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - run: |
        pip install --upgrade pip
        pip install --upgrade setuptools
        pip install -r requirements.txt
        pip install --upgrade pytest
    - name: Run tests
      run: |
        pytest tests/
