name: Test with images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - run: |
        pip install -r requirements.txt
        pip install -r test_with_sample_images/requirements.txt
    - name: Run tests
      run: |
        python3 test_with_sample_images/report.py

    - name: zip
      run: zip -r -q test_with_sample_images/results.zip test_with_sample_images/results

    - name: upload binaries to release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: test
        files: test_with_sample_images/results.zip
